LAPC-48 alif-graphics-image.bolt-fpga.wks: Allow xipImage space upto 8MB
Source: Alif Semiconductor
JIRA ID: LAPC-48
Type: Defect Fix
Disposition: Local
Description:

The size of xipImage (Linux kernel) is more than 4MB,
due to addition of graphics.cfg and nfs.cfg kernel configs.
So in the .wic scripts  we need to allow more than 4MB space
for the xipImage. Otherwise the builds fail with the below error:

-- snip --
DEBUG: Python function extend_recipe_sysroot finished
DEBUG: Executing shell function do_image_wic
INFO: Creating image(s)...
WARNING: bootloader config not specified, using defaults
ERROR: File system image of partition None is larger (4178 kB) than its allowed size 4096 kB
WARNING: <http://10.10.10.21:8080/job/BoltFPGABuildForCortexA32/ws/bolt-firmware-5.4/build/tmp/work/bolt_fpga-poky-linux-musleabi/alif-graphics-image/1.0-r0/temp/run.do_image_wic.27948>:1 exit 1 from 'BUILDDIR="<http://10.10.10.21:8080/job/BoltFPGABuildForCortexA32/ws/bolt-firmware-5.4/build"> wic create "$wks" --vars "<http://10.10.10.21:8080/job/BoltFPGABuildForCortexA32/ws/bolt-firmware-5.4/build/tmp/sysroots/bolt-fpga/imgdata/"> -e "alif-graphics-image" -o "$out/"'
ERROR: Execution of '<http://10.10.10.21:8080/job/BoltFPGABuildForCortexA32/ws/bolt-firmware-5.4/build/tmp/work/bolt_fpga-poky-linux-musleabi/alif-graphics-image/1.0-r0/temp/run.do_image_wic.27948'> failed with exit code 1:

INFO: Creating image(s)...

WARNING: bootloader config not specified, using defaults

ERROR: File system image of partition None is larger (4178 kB) than its allowed size 4096 kB

WARNING: <http://10.10.10.21:8080/job/BoltFPGABuildForCortexA32/ws/bolt-firmware-5.4/build/tmp/work/bolt_fpga-poky-linux-musleabi/alif-graphics-image/1.0-r0/temp/run.do_image_wic.27948>:1 exit 1 from 'BUILDDIR="<http://10.10.10.21:8080/job/BoltFPGABuildForCortexA32/ws/bolt-firmware-5.4/build"> wic create "$wks" --vars "<http://10.10.10.21:8080/job/BoltFPGABuildForCortexA32/ws/bolt-firmware-5.4/build/tmp/sysroots/bolt-fpga/imgdata/"> -e "alif-graphics-image" -o "$out/"'

NOTE: recipe alif-graphics-image-1.0-r0: task do_image_wic: Failed
ERROR: Task (<http://10.10.10.21:8080/job/BoltFPGABuildForCortexA32/ws/bolt-firmware-5.4/build/../layers/meta-bolt/recipes-core/images/alif-graphics-image.bb>:do_image_wic) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1650 tasks of which 1252 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
<http://10.10.10.21:8080/job/BoltFPGABuildForCortexA32/ws/bolt-firmware-5.4/build/../layers/meta-bolt/recipes-core/images/alif-graphics-image.bb>:do_image_wic
Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
Build step 'Execute shell' marked build as failure
-- snip --

Reviewed-by: Hemanth Kumar <hemanth@alifsemi.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jagadeesh@alifsemi.com>
Change-Id: I06c2edd7c8d06365382a41230cddcc62509aeeba